version: "3.6"
services:
  goapp:
    container_name: goapp
    build:
      context: ./app/
      dockerfile: Dockerfile.goapp
    environment:
      APP_PORT: ":8000"
      REDIS_HOST: "redis-go:6379"
      REDIS_USER: "admin"
      REDIS_PASS_FILE: "/run/secrets/redis_pass"
    secrets:
      - redis_pass
    networks:
      - "go_app_network"
    depends_on:
      - redis-go
    restart: always

  nginx-go:
    container_name: nginx-go
    build:
      context: ./nginx/
      dockerfile: Dockerfile.nginx
    ports:
      - 8089:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - "go_app_network"
    depends_on:
      - redis-go
    restart: always

  redis-go:
    container_name: redis-go
    build:
      context: ./redis/
      dockerfile: Dockerfile.redis
    volumes:
      - "./redis/redis.conf:/etc/redis/redis.conf"
    secrets:
      - redis_acl
    networks:
      - "go_app_network"
    restart: always
  

networks:
  go_app_network:
    name: "go_app_network"
    driver: "bridge"


secrets:
  redis_pass:
    file: "./app/RedisPass"
  redis_acl:
    file: "./redis/users.acl"
